#!/bin/bash

command=$1

function src() {
  uv run ruff check --fix
  uv run ruff format
  uv run pyrefly check
}

function infra() {
  helm lint infra/charts/pybox
  helm template infra/charts/pybox > /dev/null
}

function cicd() {
  VALUES="infra/charts/pybox/values.yaml"
  COMMIT=$(git rev-parse --short HEAD)
  
  docker build -t pybox:$COMMIT .
  
  yq e ".image.tag = \"$COMMIT\"" -i $VALUES
  
  git add $VALUES
  git commit -m "Build image pybox:$COMMIT"
  git push
}

case $command in
  "src")
    src
    ;;
  "infra")
    infra
    ;;
  "cicd")
    cicd
    ;;
  *)
    exit 1
    ;;
esac


