apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pybox.fullname" . }}-config
  labels: {{- include "pybox.labels" . | nindent 4 }}
data:
  host: {{ .Values.config.host | quote }}
  port: {{ .Values.config.port | quote }}
  workers: {{ .Values.config.workers | quote }}
