apiVersion: v1
kind: Service
metadata:
  name: {{ include "pybox.fullname" . }}-service
  labels: {{- include "pybox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      protocol: TCP
      name: http
  selector: {{- include "pybox.selectorLabels" . | nindent 4 }}
